### ISSUE TITLE
Use the new official API node wraper

### ISSUE THREAD

**Issue by m-baumgartner** [hubot-scripts/hubot-mailchimp#1]
The official node wrapper is available as 'mailchimp-api'.
Make this package use this wrapper instead of the current one.

https://www.npmjs.org/package/mailchimp-api

**Comment by stephenyeargin** [comment]
Closing this off. The official package ended up not supporting their latest version of the API and they stopped maintaining it in favor of community packages. As of this writing, we're updated to v3 with #6.
