### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by hkdobrev** [hubot-scripts/hubot-mailchimp#5]
Could you bump up the package version so the `mailchimp` command from #4 gets published?

Also you could tag these version bump commits using the releases tag as well.

Thanks!

**Comment by patcon** [comment]
I don't have push access to the npm package, but I think @m-baumgartner does. fyi, I use grunt-release to make proper releases dead simple, so it takes all of 1 second to pull one with tags, version bumps, npmjs push, etc

https://github.com/geddski/grunt-release

Also, using this hubotscript generator gives you that for free when creating future scripts:
https://github.com/desmondmorris/generator-hubot-script

Cheers! :)

**Comment by hkdobrev** [comment]
Or you could use Travis deployments which could automatically publish to npm on tagged commits. http://docs.travis-ci.com/user/deployment/npm/

**Comment by m-baumgartner** [comment]
Done.
Manually for now but that travis automation is sexy though, i'll take a look.

**Comment by m-baumgartner** [comment]
Alright Travis should now build and publish future versions of this package on it's own.
Plus, I added `travis build status` and `npm version` badges.
